dist: "bionic"

language: "python"

python:
    - "3.8"
    - "3.9"
    - "3.10"

install:
    - "pip install -U \"flake8==5.0.4\" \"mypy==0.982\" \"numpy==1.21.1\" \"scipy==1.7.1\" \"pytest==7.2.0\" \"pytest-cov==4.0.0\" \"attrs==22.1.0\" \"hypothesis==6.58.0\" \"coveralls==3.3.1\" \"sphinx<7.0.0\" \"sphinx_rtd_theme==1.2.2\""
    - "pip install ."

script:
    - "flake8 petbox/dca"
    - "mypy petbox/dca"
    - "pytest"
    - "sphinx-build -W -b html docs docs/_build/html"

notifications:
    - email: false

after_success:
    - "coveralls"
